app_admin_post:
    resource: |
        alias: app.post
        grid: app_post
        except: [ "show" ]
        templates: SyliusAdminBundle:Crud
    type: sylius.resource
    prefix: admin

app_shop_post_index:
    pattern: /shop/posts
    defaults:
        _controller: app.controller.post:indexAction
