sylius_grid:
    grids:
        app_post:
            driver:
                options:
                    class: AppBundle\Entity\Post
            fields:
                title:
                    type: string
                published_at:
                    type: datetime
                    options:
                        format: Y-m-d
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

