imports:
    - { resource: resources.yml }
    - { resource: grid.yml }


sylius_customer:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
                form:
                    default: AppBundle\Form\CustomerType
