services:
    app.admin_menu_listener:
        class: AppBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    app.controller.shop_post:
        class: AppBundle\Controller\PostController
        arguments:
            - @doctrine.orm.default_entity_manager
            - @templating

    app.rule_checker.karma:
        class: AppBundle\Promotion\KarmaRuleChecker
        tags:
            - 
                name: sylius.promotion_rule_checker
                type: karma
                label: Karma
